object GameData {

    var quests = listOf(
        Quest(
            probabilityRange = 1..2,
            name = "Dungeon Training 1",
            objective = "Basic dungeoning, loot 3 Parts.",
            encounterModifier = -40,
            rewardGold = 50,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 3..4,
            name = "Dungeon Training 2",
            objective = "Basic dungeoning, loot 3 Weapons.",
            encounterModifier = -40,
            rewardGold = 50,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 5..6,
            name = "Dungeon Training 3",
            objective = "Basic dungeoning, loot 3 Armour.",
            encounterModifier = -30,
            rewardGold = 80,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 7..8,
            name = "Dungeon Training 4",
            objective = "Basic dungeoning, loot 1 Weapons, 1 Parts and 1 Armour.",
            encounterModifier = -30,
            rewardGold = 80,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 9..10,
            name = "Dungeon Training 5",
            objective = "Basic dungeoning, loot 2 Treasures from TABLE T.",
            encounterModifier = -30,
            rewardGold = 100,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 11..12,
            name = "Map Dungeon",
            objective = "Explore a dungeon until you have mapped 2 of each different coloured room, (Red rooms x2, Grey room x2, Blue rooms x2 and Green x2).",
            encounterModifier = -20,
            rewardGold = 150,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 13..14,
            name = "Potion Hunt",
            objective = "An apprentice wizard has asked you to find any 4 potions from the dungeon to further his research.",
            encounterModifier = -20,
            rewardGold = 180,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 15..16,
            name = "Monster Hunt",
            objective = "Kill any 5 Monster that are 34 or higher on the encounter table. They have been terrorizing the locals.",
            encounterModifier = -20,
            rewardGold = 300,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 17..18,
            name = "Head of the Beast",
            objective = "The villagers want evidence that the beast terrorizing them has been killed, Obtain 1 Head (Part) from any monster.",
            encounterModifier = -20,
            rewardGold = 300,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 19..20,
            name = "Amulet of Hope",
            objective = "Since the “Amulet of Hope” was taken by two goblins, broken in two and lost deep inside a dungeon, a feeling of hopelessness has engulfed the kingdom. Now in two parts you must find its pieces and assemble it back to its former glory. Obtain 2 objective items.",
            encounterModifier = -20,
            rewardGold = 300,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 21..22,
            name = "Rescue the Villagers",
            objective = "Several Villagers have been taken by monsters and are being tortured to death, you must set them free. Kill any 5 monsters have (h) after their name on the encounter table to rescue all the villagers.",
            encounterModifier = -20,
            rewardGold = 350,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 23..24,
            name = "Monster Cull",
            objective = "Kill 10 Monster that are 34 or higher on the encounter table. Their numbers have grown too strong.",
            encounterModifier = -20,
            rewardGold = 500,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 25..26,
            name = "The Aztopaz Stone",
            objective = "A Young wizard named “Yagamou” has pinned a notice to the fireplace of your local tavern, she asks for a brave adventurer to find her a Aztopaz stone so she can finish her Staff of Light. Obtain 1 objective item.",
            encounterModifier = -15,
            rewardGold = 400,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 27..28,
            name = "Dungeon Research",
            objective = "Explore the dungeon and its features. Find 5 Monster rooms (Red Rooms) and 5 Geographic features (Green Rooms).",
            encounterModifier = -10,
            rewardGold = 200,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 29..30,
            name = "Survey Mission",
            objective = "Survey the dungeon (Roll 10 times on TABLE M – MAPPING) and report back to a concerned Hamlet of its activities.",
            encounterModifier = -10,
            rewardGold = 200,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 31..32,
            name = "Medicine",
            objective = "Obtain 4 Parts from monsters that are 43 or higher on the encounter table to heal a sickness spreading through the area.",
            encounterModifier = -5,
            rewardGold = 200,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 33..34,
            name = "Scouting Mission",
            objective = "Scout the dungeon (Roll 15 times on TABLE M – MAPPING) and report back to a concerned Village of its activities.",
            encounterModifier = -5,
            rewardGold = 300,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 35..36,
            name = "Explore Mission",
            objective = "Explore the dungeon (Roll 20 times on TABLE M – MAPPING) and report back to a concerned Town of its activities.",
            encounterModifier = -5,
            rewardGold = 400,
            rewardRep = 0,
            failureResult = "No reward",
        ),
        Quest(
            probabilityRange = 37..38,
            name = "Dungeon Delve",
            objective = "Find a lower level of the dungeon (Use Stairs or Objective Room) and explore its sub terrain tunnels (Roll 10 times on TABLE M – MAPPING).",
            encounterModifier = -5,
            rewardGold = 600,
            rewardRep = 0,
            failureResult = "No reward"
        ),
        Quest(
            probabilityRange = 39..40,
            name = "Magic Study",
            objective = "A roaming wizard has requested a Brew to further his studies. Loot any BREW OF FINER or an objective item to claim your reward.",
            encounterModifier = 0,
            rewardGold = 600,
            rewardRep = -5,
            failureResult = "No reward"
        ),
    )


    val monsters = listOf(
        Monster(1..10, "Giant rats", 25, 0, 2, 3, listOf("Disease", "Pack"), listOf("Table P")),
        Monster(11..20, "Giant bats", 25, 0, 3, 2, listOf("Fly", "Surprise", "Pack"), listOf("Table P")),
        Monster(21..25, "Giant ants", 20, 2, 2, 3, listOf("Pack"), listOf("Table P")),
        Monster(26..30, "Giant spider", 30, 2, 1, 6, listOf("Web"), listOf("Table P")),
        Monster(31..33, "Gobalotes", 25, 0, 2, 3, listOf("Pack"), listOf("Table I/W")),
        Monster(34..37, "Goblins", 25, 1, 1, 2, listOf("Pack"), listOf("Table A/ I/W")),
        Monster(38..41, "Goblin archer", 25, 1, 1, 2, listOf("Pack", "Surprise"), listOf("Table A/I/W")),
        Monster(42..42, "Goblin warlock", 30, 1, 1, 7, listOf("Dark Magic"), listOf("Table I/TA")),
        Monster(43..44, "Bear", 40, 2, 0, 10, emptyList(), listOf("Table P +5")),
        Monster(45..46, "Rat man", 30, 2, 0, 3, listOf("Pack", "Disease"), listOf("Table A/I/W")),
        Monster(47..47, "Rat man champion", 40, 2, 0, 9, listOf("Disease"), listOf("Table A/I/W")),
        Monster(48..49, "Gooatman", 40, 3, 1, 11, emptyList(), listOf("Table A/I/W")),
        Monster(50..51, "Gooatman archer", 40, 2, 1, 9, listOf("Surprise"), listOf("Table A/I/W")),
        Monster(52..52, "Gooatman priest", 40, 1, 1, 15, listOf("Dark Magic"), listOf("Table I/TA")),
        Monster(53..55, "Zombies", 35, 0, 0, 4, listOf("Disease", "Pack"), listOf("Nothing")),
        Monster(56..57, "Tricksters", 35, 1, 0, 3, listOf("Pack", "Surprise", "Dark Magic"), listOf("Table I/W +5")),
        Monster(58..59, "Imps", 35, 1, 1, 4, listOf("Fire", "Pack"), listOf("Table P/I/W +5")),
        Monster(58..61, "Orc", 45, 3, 1, 10, emptyList(), listOf("Table A/I/W +10")),
        Monster(62..65, "Orc archer", 45, 2, 1, 9, listOf("Surprise"), listOf("Table A/I/W +10")),
        Monster(66..66, "Spider queen", 40, 3, 2, 14, listOf("Web", "Surprise", "Poison"), listOf("Table P +10")),
        Monster(67..67, "Skeleton spiders", 45, 4, 2, 15, listOf("Regenerate", "Resurrection", "Web", "Surprise"), listOf("Table P +10")),
        Monster(68..68, "G. vampire bat", 45, 3, 1, 10, listOf("Fly", "Surprise", "Phase", "Resurrection"), listOf("Table P +10")),
        Monster(69..70, "Giant apes", 40, 2, 2, 8, listOf("Pack"), listOf("Table P +10")),
        Monster(71..71, "Zombie master", 50, 1, 1, 16, listOf("Disease"), listOf("Table TA +10")),
        Monster(72..72, "Skeleton", 50, 4, 1, 13, listOf("Fear", "Regenerate", "Resurrection"), listOf("Table A/W +15")),
        Monster(73..73, "Giant snake", 55, 3, 2, 16, listOf("Poison"), listOf("Table P +10")),
        Monster(74..74, "Orc champion", 55, 5, 2, 16, emptyList(), listOf("Table A/I/W +15")),
        Monster(75..75, "Ghoul", 50, 3, 3, 18, listOf("Phase", "Fear"), listOf("Table P +10")),
        Monster(76..76, "Wight", 55, 4, 3, 20, listOf("Fly", "Fear", "Resurrection"), listOf("Table I/TA")),
        Monster(77..77, "Orc warlcok", 50, 4, 2, 22, listOf("Dark Magic"), listOf("Table I/TA")),
        Monster(78..78, "Demon", 55, 4, 2, 20, listOf("Fire"), listOf("Table P/I/W +15")),
        Monster(79..79, "Ghost", 60, 4, 2, 24, listOf("Death Touch", "Ethereal", "Fear"), listOf("Table TA +15")),
        Monster(80..80, "Vampire", 65, 5, 3, 25, listOf("Dark Magic", "Fly", "Surprise", "Phase", "Resurrection"), listOf("Table I/W/TA +15")),
        Monster(81..81, "Wrath", 60, 4, 3, 28, listOf("Death Touch", "Ethereal", "Fear"), listOf("Table TB")),
        Monster(82..82, "Necromancer", 60, 5, 2, 25, listOf("Dark Magic", "Regenerate", "Resurrection"), listOf("Table I/W +20/TB")),
        Monster(83..83, "Demon lord", 55, 4, 2, 29, listOf("Fire", "Large", "Fear", "Fly"), listOf("Table P/I/W +20/TB")),
        Monster(84..84, "Ogre", 60, 5, 3, 30, listOf("Fear", "Large"), listOf("Table P+20/TB+5")),
        Monster(85..85, "Minotaur", 65, 6, 3, 33, listOf("Fear", "Large"), listOf("Table P+20/TB+5")),
        Monster(86..86, "Giant", 65, 6, 4, 35, listOf("Fear", "Large", "Stun"), listOf("Table P+20/TB+10")),
        Monster(87..87, "Troll", 60, 5, 3, 36, listOf("Large", "Fear", "Regenerate"), listOf("Table P+20/TB+10")),
        Monster(88..88, "Evil warlock", 65, 6, 3, 34, listOf("Dark Magic"), listOf("Table P+20/TB+15")),
        Monster(89..89, "Liche lord", 70, 7, 3, 35, listOf("Dark Magic", "Regenerate", "Resurrection"), listOf("Table I/W+20/TB+15")),
        Monster(90..90, "Gargoyle", 65, 7, 3, 38, listOf("Fear", "Stun", "Tough"), listOf("Table P/TB+20")),
        Monster(91..91, "Wyrm", 70, 6, 4, 40, listOf("Fear", "Attacks 2", "Large"), listOf("Table P+20/TC")),
        Monster(92..92, "Fire wyrm", 75, 7, 4, 42, listOf("Fire", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC")),
        Monster(93..93, "Frost wyrm", 75, 7, 4, 45, listOf("Freeze", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC")),
        Monster(94..94, "White dragon", 80, 7, 5, 47, listOf("Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+5")),
        Monster(95..95, "Green dragon", 80, 8, 5, 49, listOf("Poison", "Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+5")),
        Monster(96..96, "Red dragon", 85, 8, 5, 44, listOf("Fire", "Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+10")),
        Monster(97..97, "Blue dragon", 80, 7, 5, 45, listOf("Freeze", "Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+10")),
        Monster(98..98, "Black dragon", 85, 8, 5, 47, listOf("Dark Magic", "Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+15")),
        Monster(99..99, "Skeleton dragon", 90, 9, 6, 48, listOf("Ethereal", "Fly", "Fear", "Attacks 2", "Large"), listOf("Table P+20/TC+15")),
        Monster(100..100, "Golden dragon", 90, 9, 6, 50, listOf("Tough", "Stun", "Fly", "Fear", "Attacks 2", "Large", "Fire"), listOf("Table P/TC+20"))
    )
}